# Generated by Django 5.0.4 on 2024-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_rock_alter_feeding_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="turtle",
            name="rocks",
            field=models.ManyToManyField(to="main_app.rock"),
        ),
    ]
